name: pvCore
main: com.purityvanilla.pvcore.PVCore
version: 1.0
api-version: 1.20
authors: [chiralpenguin]
description: Core plugin suite for the Purity Vanilla Minecraft server
folia-supported: true
depend: [pvLib, LuckPerms]
commands:
  back:
    description: Teleport to your previous or death location
    usage: /back
    permission: pvcore.back
  blog:
    description: Get the link to the server blog
    usage: /blog
    permission: pvcore.blog
  discord:
    description: Get the link to the Discord server
    usage: /discord
    permission: pvcore.discord
  donate:
    description: Get the link to the server webstore
    usage: /donate
    permission: pvcore.donate
    aliases: [buy, shop, store, ranks, upgrade]
  faq:
    description: Displays a list of frequently asked questions
    usage: /faq
    permission: pvcore.faq
  gamemode:
    description: Change the players gamemode
    usage: /gamemode <gamemode> [player]
    permission: pvcore.gamemode
    aliases: [gma, gmc, gms, gmsp]
  help:
    description: Sends the help message for the corresponding page (default 0)
    usage: /help <page>
    permission: pvcore.help
  nick:
    description: Sets your nickname
    usage: /nick <nickname>
    permission: pvcore.nickname
    aliases: [nickname]
  nickremove:
    description: Removes your or another player's nickname
    usage: /removenick [<player>]
    permission: pvcore.nickname.remove
    aliases: [nickoff, nickclear]
  realname:
    description: Get all the players with a given nickname
    usage: /realname <nickname>
    permission: pvcore.realname
  reddit:
    description: Get the link to the server's subreddit
    usage: /reddit
    permission: pvcore.reddit
  reload:
    description: Reloads the plugin's configs and messages
    usage: /pvcore-reload
    permission: pvcore.reload
  rewards:
    description: See the servers voting rewards
    usage: /rewards
    permission: pvcore.rewards
  rules:
    description: Sends the server rules message
    usage: /rules
    permission: pvcore.rules
    aliases: [rule]
  sloc:
    description: Save the player's current location
    usage: /sloc <name>
    permission: pvcore.saveloc
    aliases: [sethome]
  dloc:
    description: Delete a saved location
    usage: /dloc <name>
    permission: pvcore.deleteloc
    aliases: [delhome]
  tloc:
    description: Teleport to a saved location
    usage: /tloc <name>
    permission: pvcore.tploc
    aliases: [home]
  rloc:
    description: Rename a saved location
    usage: /rloc <old_name> <new_name>
    permission: pvcore.renameloc
    aliases: [renamehome]
  suicide:
    description: Kills the player
    usage: /suicide
    permission: pvcore.suicide
#    aliases: [kill] - Disabled due to conflict with minecraft:kill
  teleport:
    description: Teleports the player to another player or position
    usage: /teleport <player/coordinates> [world]
    permission: pvcore.teleport
    aliases: [tp]
  tphere:
    description: Teleports a player to the player executing the command
    usage: /tphere <player>
    permission: pvcore.tphere

permissions:
  pvcore.back.on-death:
    description: Saves death positions for teleporting with /back
  pvcore.formatcodes.all:
    description: Gives access to all formatting codes in all contexts
  pvcore.formatcodes.magic:
    description: Gives access to magic (obfuscated) formatting in all contexts
  pvcore.formatcodes.nickname.all:
    description: Gives access to all formatting codes in nicknames
  pvcore.formatcodes.nickname.magic:
    description: Gives access to magic (obfuscated) formatting in nicknames
  pvcore.nickname.remove.others:
    description: Remove other player's nicknames while they are online