name: pvCore
main: com.purityvanilla.pvcore.pvCore
version: 1.0
api-version: 1.20
authors: [chiralpenguin]
description: Core plugin suite for the Purity Vanilla Minecraft server
folia-supported: true
depend: [pvLib]
commands:
  gamemode:
    description: Change the players gamemode
    usage: /gamemode <gamemode> [player]
    permission: pvcore.gamemode
    aliases: [gma, gmc, gms, gmsp]
  help:
    description: Sends the help message for the corresponding page (default 0)
    usage: /help <page>
    permission: pvcore.help
  rules:
    description: Sends the server rules message
    usage: /rules
    permission: pvcore.rules
    aliases: [rule]
  teleport:
    description: Teleports the player to another player or position
    usage: /teleport <player/coordinates> [world]
    permission: pvcore.teleport
    aliases: [tp]
  tphere:
    description: Teleports a player to the player executing the command
    usage: /tphere <player>
    permission: pvcore.tphere
